In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
password = "MysqlQ123"

connection_string = f"mysql+pymysql://root:{password}@localhost/sakila"

engine = create_engine(connection_string)

engine

Engine(mysql+pymysql://root:***@localhost/sakila)

In [5]:
import pandas as pd
def rentals_month(engine, month, year):
    
    query = f"""
    SELECT *
    FROM rental
    WHERE MONTH(rental_date) = {month}
      AND YEAR(rental_date) = {year};
    """
    
    df = pd.read_sql(query, engine)
    
    return df

In [11]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Mysql@123",
    host="localhost",
    database="sakila"
)

engine = create_engine(url)

print(engine)

Engine(mysql+pymysql://root:***@localhost/sakila)

In [12]:
import pandas as pd

query = "SELECT * FROM rental LIMIT 5"

df = pd.read_sql(query, engine)

df.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [13]:
def rentals_month(engine, month, year):

    query = f"""
    SELECT *
    FROM rental
    WHERE MONTH(rental_date) = {month}
      AND YEAR(rental_date) = {year};
    """

    df = pd.read_sql(query, engine)

    return df

In [14]:
may_rentals = rentals_month(engine, 5, 2005)

may_rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [15]:
def rental_count_month(df, month, year):

    column_name = f"rentals_{month:02d}_{year}"

    rental_count = (
        df.groupby("customer_id")
        .size()
        .reset_index(name=column_name)
    )

    return rental_count

In [16]:
may_counts = rental_count_month(may_rentals, 5, 2005)

may_counts.head()

   customer_id  rentals_05_2005
0            1                2
1            2                1
2            3                2
3            5                3
4            6                3

In [17]:
june_rentals = rentals_month(engine, 6, 2005)

june_counts = rental_count_month(june_rentals, 6, 2005)

june_counts.head()

   customer_id  rentals_06_2005
0            1                7
1            2                1
2            3                4
3            4                6
4            5                5

In [18]:
def compare_rentals(df1, df2):

    combined = pd.merge(df1, df2, on="customer_id", how="inner")

    col1 = combined.columns[1]
    col2 = combined.columns[2]

    combined["difference"] = combined[col2] - combined[col1]

    return combined

In [19]:
comparison = compare_rentals(may_counts, june_counts)

comparison.head()

   customer_id  rentals_05_2005  rentals_06_2005  difference
0            1                2                7           5
1            2                1                1           0
2            3                2                4           2
3            5                3                5           2
4            6                3                4           1